### ISSUE TITLE
cant use "or" query

### ISSUE THREAD

**Issue by mouyong** [matrix-lab/laravel-advanced-search#4]
![image](https://user-images.githubusercontent.com/10336437/83582502-4293e700-a574-11ea-8949-8e00bc7783e1.png)

![image](https://user-images.githubusercontent.com/10336437/83582540-5ccdc500-a574-11ea-82ba-991f8157a86a.png)

**Comment by zhuzhichao** [comment]
```
'height' => [
            'gt'  => '180',
            'lt'  => '160',
            'mix' => 'or',
        ],
```

or 只能作用于单个字段的多个条件。

最外层只能是 and ，如果需要某几个字段有 or 逻辑（例如你这里的 no 和 name ），然后这个 or 逻辑和其他是 and ，需要你写个单独的查询逻辑，可以参考 readme 的一些方法（例如闭包或者模型的 scope 方法）。

由于 laravel 查询的规则，如果查询的同级里面，有一个  or ，那么全部都是 or 关系，所以这里为了避免这种情况，最外层的关系全部是  and， 如果需要多字段or，请自行构造查询逻辑。
