### ISSUE TITLE
cant filter null query

### ISSUE THREAD

**Issue by mouyong** [matrix-lab/laravel-advanced-search#5]
![image](https://user-images.githubusercontent.com/10336437/83587041-a58b7b00-a580-11ea-814f-c086e5525a26.png)

**Comment by zhuzhichao** [comment]
如果对前端传值有要求的话，建议使用 request 的 rule 进行预处理，是否符合  string 的规则。

如果不使用 rule 的话，建议在下文拼接字符串之前再做判断。

fireInput 并不能将 数组 转换为字符串。

**Comment by zhuzhichao** [comment]
如果对前端传值有要求的话，建议使用 request 的 rule 进行预处理，是否符合 string 的规则。

如果不使用 rule 的话，建议在下文拼接字符串之前再做判断。

fireInput 并不能将 数组 转换为字符串。

**Comment by zhuzhichao** [comment]
我稍后发个新版本， fireInput 把空数组过滤掉，但是如果非空数组仍然会被传入闭包。

另外：

建议使用 request 的 rule 进行预处理，是否符合 string 的规则。

如果不使用 rule 的话，建议在下文拼接字符串之前再做判断。

**Comment by zhuzhichao** [comment]
v0.2.9  可以将空数组过滤掉了。更新一下版本就可以了。

谢谢你的反馈！ 🌹
